# Generated by Django 4.2.6 on 2024-04-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_colleges_location_poll_is_off_cumpus_myuser_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='College',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.colleges'),
        ),
        migrations.AddField(
            model_name='poll',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.location'),
        ),
    ]
